jwt:
  expirationTime: 86400000 # 1000 * 60 * 60 * 24 (24 hours)
springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transport_tycoon?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: app_user
    password: secret_password
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
